name: "Release : Executables"

on:
  # Triggered manually
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name"
        required: true
  # Triggered by release-nocodb.yml
  workflow_call:
    inputs:
      tag:
        description: "Tag name"
        required: true
        type: string
    secrets:
      NC_GITHUB_TOKEN:
        required: true
jobs:
  build-executables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get pnpm store directory
        shell: bash
        run: |
          sed -i '/^use-node-version/d' .npmrc
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # for building images for all platforms these libraries are required in Linux
      - name: Install QEMU and ldid
        run: |
          sudo apt update
          # Install qemu
          sudo apt install qemu binfmt-support qemu-user-static
          # install ldid
          git clone https://github.com/daeken/ldid.git
          cd ./ldid
          ./make.sh
          sudo cp ./ldid /usr/local/bin

      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.1

      - name : Install nocodb, other dependencies and build executables
        run: |
          cd ./scripts/pkg-executable
          
          # downgrade sqlite3 to 5.1.6 until build related issues are resolved
          # https://github.com/TryGhost/node-sqlite3/issues/1748        
          node ../downgradeSqlite.js

          # Install nocodb version based on provided tag name
          npm i -E nocodb@${{ github.event.inputs.tag || inputs.tag }}
          

          # install npm dependendencies
          npm i

          # Build sqlite binaries for all platforms
          ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=win32 --fallback-to-build --target_arch=x64 --target_libc=unknown
          ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=win32 --fallback-to-build --target_arch=ia32 --target_libc=unknown
          ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=darwin --fallback-to-build --target_arch=x64 --target_libc=unknown
          ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=darwin --fallback-to-build --target_arch=arm64 --target_libc=unknown
          ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=linux --fallback-to-build --target_arch=x64 --target_libc=glibc
          ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=linux --fallback-to-build --target_arch=arm64 --target_libc=glibc
          ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=linux --fallback-to-build --target_arch=x64 --target_libc=musl
          ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=linux --fallback-to-build --target_arch=arm64 --target_libc=musl

          # clean up code to optimize size
          npx modclean --patterns="default:*" --ignore="nc-lib-gui/**,nocodb/**,dayjs/**,express-status-monitor/**,sqlite3/**" --run
          
          mkdir ./mac-dist
          mkdir ./dist
                
          # build darwin x64 executable
          npm uninstall sharp
          npm install --cpu=x64 --os=darwin sharp
          npx --yes pkg@5.8.1 . --compress GZip -t node18-macos-x64 -o Noco-macos-x64
          mv ./Noco-macos-x64 ./mac-dist/
        
          # build darwin arm64 executable
          npm uninstall sharp
          npm install --cpu=arm64 --os=darwin sharp
          npx --yes pkg@5.8.1 . --compress GZip -t node18-macos-arm64 -o Noco-macos-arm64
          mv ./Noco-macos-arm64 ./mac-dist/
          
        
          # build linux x64 executable
          npm uninstall sharp
          npm install --cpu=x64 --os=linux sharp
          npx --yes pkg@5.8.1 . --compress GZip -t node18-linux-x64 -o Noco-linux-x64
          mv ./Noco-linux-x64 ./dist/

          # build linux arm64 executable
          npm uninstall sharp
          npm install --cpu=arm64 --os=linux sharp
          npx --yes pkg@5.8.1 . --compress GZip -t node18-linux-arm64 -o Noco-linux-arm64
          mv ./Noco-linux-arm64 ./dist/


          # build windows x64 executable
          npm uninstall sharp
          npm install --cpu=x64 --os=win32 sharp
          npx --yes pkg@5.8.1 . --compress GZip -t node18-win-x64 -o Noco-win-x64.exe
          mv ./Noco-win-x64.exe ./dist/

          # build windows arm64 executable
          npm uninstall sharp
          npm install --cpu=arm64 --os=win32 sharp
          npx --yes pkg@5.8.1 . --compress GZip -t node18-win-arm64 -o Noco-win-arm64.exe
          mv ./Noco-win-arm64.exe ./dist/

      - uses: actions/upload-artifact@master
        with:
          name: ${{ github.event.inputs.tag || inputs.tag }}
          path: scripts/pkg-executable/mac-dist
          retention-days: 1